#!/usr/bin/env python3
"""Graphviz rendering of the same architecture spec, as a structural check.

This is a *review* artifact, not a paper figure. ``dot``'s auto-layout will not
match the hand-placed matplotlib figure, and that is the point: if an edge or a
containment relationship exists in one drawing and not the other, the spec and a
renderer have drifted apart.

Run ``--check`` to have it assert that what it drew matches
``ArchSpec.edge_keys()`` exactly, and print the edge table.

The Python ``graphviz`` wrapper is optional -- it is a thin shim over the ``dot``
binary. When it is absent this falls back to writing the ``.dot`` source and
invoking ``/usr/bin/dot`` directly, so nothing about the camera-ready figure
depends on that package being installed.

Usage
-----
    python paper_figures/make_arch_dot.py --out paper_figures/out
    python paper_figures/make_arch_dot.py --check
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from arch_spec import (  # noqa: E402
    ELIDED,
    Topology,
    build_spec,
    gpu_layout,
)

# Node kind -> (graphviz shape, fill, pen style). Mirrors the matplotlib
# encoding closely enough to be recognisable side by side.
DOT_NODE_STYLE = {
    "inproc_obj": ("box", "#E8F0FA", "solid", "#2B5D8A"),
    "ray_actor": ("box", "#E6F4EA", "solid", "#2E7D4F"),
    "policy": ("box", "#FFFFFF", "dashed", "#C2571A"),
    "engine": ("box", "#F1EAFB", "solid", "#5B3E96"),
    "trainer": ("box", "#FDF3E0", "solid", "#A9741A"),
}

DOT_EDGE_STYLE = {
    "dispatch": ("solid", "normal", "#333333"),
    "http_migrate": ("dashed", "normal", "#B14A12"),
    "produce": ("solid", "normal", "#333333"),
    "consume": ("solid", "both", "#333333"),
    "colocate": ("dotted", "none", "#666666"),
}


def _esc(s: str) -> str:
    return s.replace('"', '\\"').replace("\n", "\\n")


def build_dot(spec) -> tuple[str, list[tuple[str, str, str]]]:
    """Emit the digraph source and the edge keys actually written into it.

    Owner relationships become ``subgraph cluster_*`` so containment shows up as
    containment here too, not as an extra arrow that does not exist in the spec.

    Returning the drawn edge keys alongside the source keeps ``--check`` honest:
    it compares what this function emitted against ``ArchSpec.edge_keys()``
    rather than re-parsing the DOT text, which is fragile (the graph title alone
    contains a literal ``->``).
    """
    topo = spec.topology
    layout = gpu_layout(topo)
    engine_row = " | ".join(sp.label for sp in layout.engines)
    trainer_row = " | ".join(sp.label for sp in layout.train_groups)
    gpu_row = " | ".join(
        "..." if g is ELIDED else str(g) for g in layout.columns
    )

    script = os.path.abspath(__file__)
    rel = os.path.relpath(script, os.getcwd())
    if not rel.startswith(os.pardir):
        script = rel

    lines = [
        f"// Generated by {script} -- do not hand-edit; regenerate instead.",
        "digraph streaming_arch {",
        # splines=spline, not ortho: dot refuses to place edge labels on
        # orthogonal routing, and the labels are the whole point of the check.
        '  graph [rankdir=TB, splines=spline, nodesep=0.45, ranksep=0.9, '
        'fontname="Helvetica", labelloc=t, '
        f'label="streaming colocated RL -- data plane\\n{_esc(topo.describe())}"];',
        '  node [fontname="Helvetica", fontsize=10, style="filled", margin="0.16,0.10"];',
        '  edge [fontname="Helvetica", fontsize=8];',
    ]

    owners = {n.owner for n in spec.nodes if n.owner}
    for node in spec.nodes:
        if node.id in owners:
            continue  # emitted below, as a cluster wrapping its children
        shape, fill, pen, pencolor = DOT_NODE_STYLE[node.kind]
        label = node.label
        # Record nesting under rankdir=TB: the outer {} stacks title over chips,
        # the inner {} flips back to a horizontal chip row.
        if node.id == "engines":
            label = f"{{{node.label}|{{{engine_row}}}}}"
            shape = "record"
        elif node.id == "trainers":
            # Include the shared GPU row here so the dot version still carries
            # the colocation information the matplotlib figure draws as a lane.
            label = f"{{{node.label}|{{{trainer_row}}}|GPUs|{{{gpu_row}}}}}"
            shape = "record"
        elif node.sublabel:
            label = f"{node.label}\\n{node.sublabel}"
        lines.append(
            f'  {node.id} [shape={shape}, label="{_esc(label)}", fillcolor="{fill}", '
            f'style="filled,{pen}", color="{pencolor}"];'
        )

    for owner_id in sorted(owners):
        owner = spec.node(owner_id)
        shape, fill, pen, pencolor = DOT_NODE_STYLE[owner.kind]
        lines += [
            f"  subgraph cluster_{owner_id} {{",
            f'    label="{_esc(owner.label)}\\n{_esc(owner.sublabel)}";',
            f'    style="filled,{pen}"; fillcolor="{fill}"; color="{pencolor}";',
            '    fontsize=10; labeljust=l;',
            # An invisible anchor so edges can attach to the owner itself.
            f'    {owner_id} [shape=point, width=0.01, style=invis];',
        ]
        for child in spec.children_of(owner_id):
            cshape, cfill, cpen, cpencolor = DOT_NODE_STYLE[child.kind]
            clabel = f"{child.label}\\n{child.sublabel}"
            lines.append(
                f'    {child.id} [shape={cshape}, label="{_esc(clabel)}", '
                f'fillcolor="{cfill}", style="filled,{cpen}", color="{cpencolor}"];'
            )
        lines.append("  }")

    drawn: list[tuple[str, str, str]] = []
    for e in spec.edges:
        style, arrowhead, color = DOT_EDGE_STYLE[e.kind]
        label = "\\n".join((e.label, *e.detail))
        extra = ""
        if e.kind == "consume":
            extra = ", dir=both"
        if e.kind == "colocate":
            extra = ", dir=none, constraint=true"
        lines.append(
            f'  {e.src} -> {e.dst} [label="{_esc(label)}", style={style}, '
            f'color="{color}", fontcolor="{color}"{extra}];'
        )
        drawn.append((e.src, e.dst, e.label))

    lines.append("}")
    return "\n".join(lines), sorted(drawn)


def render(dot_source: str, stem: str) -> list[str]:
    """Write ``<stem>.dot`` and render PDF + PNG, preferring the Python wrapper."""
    dot_path = f"{stem}.dot"
    with open(dot_path, "w") as f:
        f.write(dot_source)

    written = [dot_path]
    try:
        import graphviz  # noqa: F401

        from graphviz import Source

        src = Source(dot_source)
        for fmt in ("pdf", "png"):
            src.render(filename=stem, format=fmt, cleanup=False)
            written.append(f"{stem}.{fmt}")
        # Source.render leaves an extension-less copy of the source behind.
        if os.path.exists(stem):
            os.replace(stem, dot_path)
        return written
    except ImportError:
        pass

    dot_bin = shutil.which("dot")
    if dot_bin is None:
        print("[arch-dot] neither the python 'graphviz' package nor the 'dot' "
              f"binary is available; wrote {dot_path} only", file=sys.stderr)
        return written
    for fmt in ("pdf", "png"):
        out = f"{stem}.{fmt}"
        subprocess.run([dot_bin, f"-T{fmt}", dot_path, "-o", out], check=True)
        written.append(out)
    return written


def check(spec, drawn: list[tuple[str, str, str]]) -> int:
    """Assert the emitted digraph carries exactly the spec's edge set."""
    expected = spec.edge_keys()
    print(f"{'src':<14}{'dst':<14}label")
    print("-" * 72)
    for e in spec.edges:
        print(f"{e.src:<14}{e.dst:<14}{e.label}")
        print(f"{'':<28}source: {e.source}")
    if drawn != expected:
        print("\n[arch-dot] EDGE SET MISMATCH", file=sys.stderr)
        for k in sorted(set(expected) - set(drawn)):
            print(f"  in spec, not drawn: {k}", file=sys.stderr)
        for k in sorted(set(drawn) - set(expected)):
            print(f"  drawn, not in spec: {k}", file=sys.stderr)
        return 1
    print(f"\n[arch-dot] OK: {len(expected)} edges, spec and digraph agree")
    return 0


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--out", default="paper_figures/out")
    p.add_argument("--name", default="arch_dot")
    p.add_argument("--num-gpus", type=int, default=8)
    p.add_argument("--train-tp", type=int, default=2)
    p.add_argument("--infer-tp", type=int, default=1)
    p.add_argument("--check", action="store_true",
                   help="verify the drawn edge set matches the spec, and print "
                        "the edge -> file:line provenance table")
    args = p.parse_args(argv)

    spec = build_spec(Topology(total_gpus=args.num_gpus, train_tp=args.train_tp,
                               infer_tp=args.infer_tp))
    dot_source, drawn = build_dot(spec)

    if args.check:
        return check(spec, drawn)

    os.makedirs(args.out, exist_ok=True)
    for path in render(dot_source, os.path.join(args.out, args.name)):
        print(f"[arch-dot] wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
